services:
  backend:
    build: ./backend
    privileged: true
    network_mode: host
    volumes:
      - ./backend/data:/app/data
    restart: unless-stopped
    environment:
      - PORT=21081

  frontend:
    build: ./frontend
    ports:
      - "21080:80"
    restart: unless-stopped
    depends_on:
      - backend
